Change: SIA control previously prohibited env variables

diff --git a/sia b/sia
--- a/sia
+++ b/sia
@@ -35,19 +35,19 @@ configTemplate=".sia-config-template.sh"
 messageScript=".sia-messages.sh"
 
 ### If verbosity defined: set it
-case "${1:-}" in;
-    silent|-s|0)
+case "${1:-}" in
+    --silent|0)
         verbosity=0
         shift
         ;;
-    quiet|-q|1)
+    --quiet|1)
         verbosity=1
         shift
         ;;
     2)
         shift
         ;;
-    debug|verbose|-d|-v|3|loud)
+    --debug|--verbose|3|--loud)
         verbosity=3
         shift
         ;;
@@ -62,7 +62,7 @@ shift || true
 #  - uncomment to block relevant commands during testing
 
 #docker() {
-#  echo "[MOCK] docker $@"
+#    echo "[MOCK] docker $@"
 #}
 #git() {
 #    echo "[MOCK] git $@"
@@ -73,6 +73,40 @@ shift || true
 if ! docker compose version >/dev/null 2>&1 && command -v docker-compose >/dev/null 2>&1; then
     docker() { if [[ "$1" == "compose" ]]; then shift; command docker-compose "$@"; else command docker "$@"; fi; }
 fi
+
+# VERBOSITY AND SEMANTICS
+# ANSI Color Codes
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+BLUE='\033[0;34m'
+BOLD='\033[1m'
+NC='\033[0m' # No Color
+# Default verbosities: 0: Silent, 1: Errors only, 2: Standard (Info), 3: Debug (Trace)
+
+log() {
+    local msg_lvl=$1; shift
+    [[ $verbosity -lt $msg_lvl ]] && return 0
+    
+    # Send errors (Level 1) to stderr, everything else to stdout
+    if [[ $msg_lvl -eq 1 ]]; then
+        echo -e "$*" >&2
+    else
+        echo -e "$*"
+    fi
+}
+
+# SEMANTIC WRAPPERS
+# These call log() internally so you don't have to remember the numbers.
+
+msg_error()   { log 1 "${RED}[ERROR]${NC}   $*"; }
+msg_usage()   { log 2 "${YELLOW}[USAGE]${NC}   $*"; }
+msg_warn()    { log 2 "${YELLOW}[WARN]${NC}    $*"; }
+msg_info()    { log 2 "${BLUE}[INFO]${NC}    $*"; }
+msg_success() { log 2 "${GREEN}[SUCCESS]${NC} $*"; } # SUCCESS is longest, so it has 1 space
+msg_debug()   { log 3 "${BOLD}[DEBUG]${NC}   $*"; }
+msg_normal()  { log 2 "          $*"; }           # 10 spaces to match the tags above
+msg_header()  { log 2 "\n${BOLD}== $* ==${NC}"; }
 
 ## Help :
 #  - Accepts one extra argument
@@ -121,7 +155,7 @@ errExit () {
             errorDesc="Improper configuration!"
             ;;
         3)
-            errorDesc="Unable to generate a secure secret key. Please install OpenSSL and try again or manually add a 32 byte 64 digit hex key to the $envFile file."
+            errorDesc="No known number generator!"
             ;;
         404)
             errorDesc="Could not curl replacement config template. Check internet/repo!"
@@ -335,16 +369,16 @@ envCommandListEdit () {
                     case "$REPLY" in
                         1)
                             read -p "Enter value for $key: " userInput
-                            editAnyArray $arrayName "$key=$userInput"
-                            exitScriptGoodWithMessage $exitMessage
+                            editAnyArray $arrayName "$key=$userInput" && editEnv "$key=$userInput"
+                            startCheck
                             ;;
                         2)
-                            editAnyArray $arrayName "$key"
-                            exitScriptGoodWithMessage $exitMessage
+                            editAnyArray $arrayName "$key"  && editEnv "$key"
+                            startCheck
                             ;;
                         3)
-                            editAnyArray $arrayName "$key" "rm"
-                            exitScriptGoodWithMessage $exitMessage
+                            editAnyArray $arrayName "$key" "rm" && checkArray envVars
+                            startCheck
                             ;;
                         4)
                             exitScriptGoodWithMessage "Exiting."
@@ -402,7 +436,7 @@ envCommand () {
                     errExit 1
                 fi
             done
-            editAnyArray $arrayName "$key=$value"
+            editAnyArray $arrayName "$key=$value" && editEnv "$key=$value"
             msg_success "Successfully added/updated '$key=$value' in array '$arrayName'."
             msg_info "Run $scriptName to apply changes."
             ;;
@@ -460,7 +494,7 @@ ensureSecretKey () {
     # Check if key exists and generate one if it doesn't
     touch "$envFile"
     if ! grep -q "^SEARXNG_SECRET=" "$envFile" 2>/dev/null; then
-        echo "Generating secret key..."
+        msg_debug "Generating secret key..."
         local secretKey
         # Generate the key
         # Try OpenSSL :
@@ -476,12 +510,15 @@ ensureSecretKey () {
             fi
             # Error out if no easy way to generate a secure key :
             if [[ -z "$secretKey" ]]; then
+                msg_error "Couldn't find a way to generate a truly random number!"
+                msg_debug "$appName tried OpenSSL, od, and python3!"
+                msg_info "Please install OpenSSL and try again or manually add a 32 byte 64 digit hex key to the $envFile file."
                 errExit 3
             fi
         fi
         # Append to .env:
 #        echo "$secretKey"
-        editEnv "SEARXNG_SECRET=$secretKey"
+        editAnyArray envVars "SEARXNG_SECRET=$secretKey" && editEnv "SEARXNG_SECRET=$secretKey"
         return 0
     fi
 }
@@ -510,19 +547,19 @@ setupFunc () {
                             msg_debug "Selected: $REPLY: $opt ($selectedFile). Making sure it's present..."
                             # Check file is present
                             if [[ ! -f $selectedFile ]]; then
-                                msg_error "Compose file $selectedFile not found!"
+                                msg_error "YAML file $selectedFile not found!"
                                 errExit 2
                             fi
-
+                            msg_debug "YAML found!"
                             # Create or Update .env
-                            editEnv "COMPOSE_FILE=$selectedFile"
+                            editAnyArray envVars "COMPOSE_FILE=$selectedFile" && editEnv "COMPOSE_FILE=$selectedFile"
                             ensureSecretKey
-                            editEnv "SETUP_COMPLETE=true"
+                            editAnyArray envVars "SETUP_COMPLETE=true" && editEnv "SETUP_COMPLETE=true"
                             msg_debug "Configuration saved to "$envFile"."
 
                             # Check if previously run / need to restart
                             if [[ $dontRestart -eq 0 ]] && grep -q "^PREVIOUSLY_RUN=true" "$envFile" 2>/dev/null; then
-                                msg_info "Previous run detected: automatically restarting..."
+                                msg_debug "Previous run detected: automatically restarting..."
                                 startCheck
                             fi
                             break
@@ -552,6 +589,8 @@ startCheck () {
         startMes_firstStart
         setupFunc 1
     fi
+    # Re-source modified config
+    source "$scriptWorkingDir/$configScript"
     # Validate state
 #    checkArray envVars
     if grep -q "^PREVIOUSLY_RUN=true" "$envFile" 2>/dev/null; then
@@ -560,7 +599,7 @@ startCheck () {
         msg_success "Valid configuration - Starting for the first time, enjoy!"
         # Append to .env:
         if ! grep -q "^PREVIOUSLY_RUN=true" "$envFile" 2>/dev/null; then
-            editEnv "PREVIOUSLY_RUN=true"
+            editAnyArray envVars "PREVIOUSLY_RUN=true" && editEnv "PREVIOUSLY_RUN=true"
         fi
     fi
     docker compose up -d --force-recreate
@@ -579,7 +618,7 @@ fi
 # If first setup or missing local config, create
 if [[ ! -f "$configScript" ]]; then
     if [[ -f "$configTemplate" ]]; then
-        msg_info "Creating local config from template..."
+        msg_debug "Creating local config from template..."
         cp "$configTemplate" "$configScript"
         chmod 600 "$configScript"  # protect potential secrets
     else
@@ -606,7 +645,7 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
     case "$firstArg" in
         start|"")
             # Default
-            msg_header "$appName Starting and validating configuration..."
+            msg_normal "$appName Starting and validating configuration..."
             # Check for all dependencies
             checkDeps
             # Start and run setup if needed
@@ -672,7 +711,7 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
     esac
 fi
 # Note: Reserved first arguments for verbosity:
-# - silent / -s / 0
-# - quiet / -q / 1
+# - --silent / 0
+# - --quiet / 1
 # - 2 (default)
-# - debug / verbose / -d / -v / 3 / loud
+# - --debug / --verbose / 3 / --loud
